import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'my';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary - Comprehensive coverage for all pages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.discover': 'Discover',
    'nav.myKitchen': 'My Kitchen',
    'nav.chat': 'Chat',
    'nav.profile': 'Profile',
    'nav.askAI': 'Ask AI',
    'nav.recipes': 'Recipes',
    'nav.kitchen': 'Kitchen',
    'nav.signIn': 'Sign In',
    'nav.logout': 'Logout',
    
    // Home Page
    'home.welcome': 'Welcome back',
    'home.whatToCook': 'What would you like to cook today?',
    'home.aiAssistant': 'AI Assistant',
    'home.aiAssistantDesc': 'Get cooking help & recipe ideas',
    'home.discoverRecipes': 'Discover Recipes',
    'home.discoverDesc': 'Browse thousands of recipes',
    'home.myKitchen': 'My Kitchen',
    'home.myKitchenDesc': 'Collections & saved recipes',
    'home.createRecipe': 'Create Recipe',
    'home.createRecipeDesc': 'Share your culinary creations',
    'home.mealPlan': 'Meal Plan',
    'home.mealPlanDesc': 'Plan your week',
    'home.askAI': 'Ask AI Chef',
    'home.suggestedForYou': 'Suggested for You',
    'home.viewAll': 'View All',
    
    // Recipe Card
    'recipe.view': 'View Recipe',
    'recipe.edit': 'Edit',
    'recipe.servings': 'servings',
    
   // Recipe Detail
    'recipeDetail.back': 'Back',
    'recipeDetail.failedToLoad': 'Failed to load recipe.',
    'recipeDetail.servings': 'servings',
    'recipeDetail.startCooking': 'Start Cooking',
    'recipeDetail.ingredients': 'Ingredients',
    'recipeDetail.instructions': 'Instructions',
    'recipeDetail.noStepsProvided': 'No steps provided.',
    'recipeDetail.reviews': 'Reviews',
    'recipeDetail.leaveReview': 'Leave Your Review',
    'recipeDetail.shareExperience': 'Share your experience with this recipe... (optional)',
    'recipeDetail.submitReview': 'Submit Review',
    'recipeDetail.submitting': 'Submitting...',
    'recipeDetail.loginToReview': 'Please log in to leave a review.',
    'recipeDetail.noReviews': 'No reviews yet. Be the first!',
    'recipeDetail.star': 'star',
    'recipeDetail.stars': 'stars',
    'recipeDetail.anonymous': 'Anonymous',
    'recipeDetail.saved': 'Saved',
    'recipeDetail.removed': 'Removed',
    'recipeDetail.recipeAdded': 'Recipe added to your saved list.',
    'recipeDetail.recipeRemoved': 'Recipe removed from saved.',
    'recipeDetail.actionFailed': 'Action failed',
    'recipeDetail.unableToUpdate': 'Unable to update saved recipes',
    'recipeDetail.submitted': 'Submitted',
    'recipeDetail.thankYou': 'Thank you for your feedback!',
    'recipeDetail.failed': 'Failed',
    'recipeDetail.unableToSubmit': 'Unable to submit feedback',
    'recipeDetail.loginRequired': 'Login required',
    'recipeDetail.pleaseLogin': 'Please log in to submit feedback.',
    'recipeDetail.ratingRequired': 'Rating required',
    'recipeDetail.selectRating': 'Please select a star rating.',
    'recipeDetail.loadedSteps': 'Loaded {count} steps',
    'recipeDetail.noStepsCheck': 'Check the instructions section.',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.filters': 'Filters',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.clear': 'Clear',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.page': 'Page',
    'common.of': 'of',
    'common.recipe': 'recipe',
    'common.recipes': 'recipes',
    
    // Index/Home Page
    'index.todaysPlan': "Today's Plan",
    'index.from': 'from',
    'index.mealsPlanned': 'meals planned',
    'index.startCooking': 'Start Cooking',
    'index.viewPlan': 'View Plan',
    'index.orAskAnything': 'Or ask me anything else',
    'index.whatToCook': 'What should I cook today?',
    'index.lookingDifferent': 'Looking for something different?',
    'index.askAboutCuisine': 'Ask me anything about Myanmar cuisine',
    'index.searchPlaceholder': "Try 'quick dinner' or 'use chicken'...",
    'index.useChicken': 'Use chicken',
    'index.quickMeals': 'Quick meals',
    'index.spicyDishes': 'Spicy dishes',
    'index.healthy': 'Healthy',
    'index.active': 'Active',
    'index.continueWhereLeft': 'Continue where you left off',
    'index.started': 'Started',
    'index.resumeCooking': 'Resume Cooking →',
    'index.tryTonight': 'Try these tonight',
    'index.seeAll': 'See all →',
    'index.needMore': 'Need more?',
    'home.forYou': 'For you',
    'home.forYouSubtitle': 'Personalized recommendations just for you',
    'home.seeAll': 'See all',
    'index.mealPlans': 'Meal Plans',
    'index.myKitchen': 'My Kitchen',
    'index.createRecipe': 'Create Recipe',
    'index.browseAll': 'Browse All',
    'index.youCooked': "You've cooked",
    'index.viewHistory': 'View your cooking history →',
    'index.aiCookingAssistant': 'Your AI cooking assistant for Myanmar cuisine',
    'index.fromQuestionToDinner': 'From "What should I cook?" to dinner on the table. In 30 seconds.',
    'index.getStarted': 'Get Started',
    'index.signIn': 'Sign In',
    'index.joinHomeCooks': 'Join home cooks discovering authentic Myanmar recipes',
    'index.aiAssistant': 'AI Assistant',
    'index.aiAssistantDesc': 'Ask what to cook. Get instant Myanmar recipe suggestions based on what you have.',
    'index.stepByStep': 'Step-by-Step',
    'index.stepByStepDesc': 'Follow guided cooking with timers. Ask AI questions while you cook.',
    'index.mealPlanning': 'Meal Planning',
    'index.mealPlanningDesc': 'Plan your week in 5 minutes. Never waste time deciding meals again.',
    'index.tryRecipes': 'Try these recipes',
    'index.popularDishes': 'Popular Myanmar dishes to get you started',
    'index.startCookingToday': 'Start Cooking Today',
    'index.freeToUse': 'Free to use. No credit card required.',
    
    // Discover Page
    'discover.title': 'Recipes',
    'discover.subtitle': 'Discover authentic Myanmar cuisine',
    'discover.forYou': 'For You',
    'discover.community': 'Community',
    'discover.apply': 'Apply Filters',
    'discover.searchPlaceholder': 'Search recipes or ingredients...',
    'discover.noSuggestions': 'No suggestions found.',
    'discover.suggestions': 'Suggestions',
    'discover.trending': 'Trending',
    'discover.popular': 'Popular',
    'discover.quickMeals': 'Quick meals',
    'discover.clear': 'Clear',
    'discover.filters': 'Filters',
    'discover.reset': 'Reset',
    'discover.diet': 'Diet',
    'discover.difficulty': 'Difficulty',
    'discover.maxTime': 'Max Time',
    'discover.any': 'Any',
    'discover.omnivore': 'omnivore',
    'discover.vegetarian': 'vegetarian',
    'discover.vegan': 'vegan',
    'discover.easy': 'Easy',
    'discover.medium': 'Medium',
    'discover.hard': 'Hard',
    'discover.maxCookTime': 'Max Cook Time',
    'discover.recipesFound': 'recipes found',
    'discover.recipeFound': 'recipe found',
    'discover.noRecipes': 'No recipes found',
    'discover.tryAdjusting': 'Try adjusting your filters or search for something else',
    'discover.clearAllFilters': 'Clear all filters',
    'discover.previous': 'Previous',
    'discover.next': 'Next',
    'discover.page': 'Page',
    'discover.saved': 'Saved',
    'discover.removed': 'Removed',
    'discover.recipeAdded': 'Recipe added to your saved list.',
    'discover.recipeRemoved': 'Recipe removed from saved.',
    'discover.actionFailed': 'Action failed',
    
    // Login Page
    'login.welcomeBack': 'Welcome back',
    'login.signInDesc': 'Sign in to save recipes and chat with the assistant',
    'login.usernameOrEmail': 'Username or Email',
    'login.usernamePlaceholder': 'username or email',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot password?',
    'login.rememberMe': 'Remember me',
    'login.signingIn': 'Signing in...',
    'login.signIn': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up',
    'login.termsAgreement': 'By continuing, you agree to our Terms and Privacy Policy.',
    'login.loginFailed': 'Login failed. Please check your credentials.',
    
    // Register Page
    'register.createAccount': 'Create your account',
    'register.joinDesc': 'Join thousands cooking Myanmar cuisine',
    'register.name': 'Full Name',
    'register.namePlaceholder': 'Your name',
    'register.username': 'Username',
    'register.usernamePlaceholder': 'Choose a username',
    'register.email': 'Email',
    'register.emailPlaceholder': 'your@email.com',
    'register.password': 'Password',
    'register.passwordPlaceholder': '••••••••',
    'register.confirmPassword': 'Confirm Password',
    'register.agreeToTerms': 'I agree to the Terms and Privacy Policy',
    'register.creatingAccount': 'Creating account...',
    'register.signUp': 'Sign Up',
    'register.alreadyHaveAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.passwordMismatch': 'Passwords do not match',
    'register.mustAgreeTerms': 'You must agree to the terms',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.memberSince': 'Member since',
    'profile.activityOverview': 'Activity Overview',
    'profile.recipesCreated': 'Recipes Created',
    'profile.recipesSaved': 'Recipes Saved',
    'profile.cookingSessions': 'Cooking Sessions',
    'profile.accountInfo': 'Account Information',
    'profile.preferences': 'Cooking Preferences',
    'profile.security': 'Security',
    'profile.saveChanges': 'Save Changes',
    'profile.savingChanges': 'Saving changes...',
    
    // My Kitchen Page
    'myKitchen.title': 'My Kitchen',
    'myKitchen.savedRecipes': 'Saved Recipes',
    'myKitchen.myRecipes': 'My Recipes',
    'myKitchen.collections': 'Collections',
    'myKitchen.mealPlans': 'Meal Plans',
    'myKitchen.noSaved': 'No saved recipes yet',
    'myKitchen.startSaving': 'Start saving your favorite recipes',
    'myKitchen.browseRecipes': 'Browse Recipes',
    
    // Collections Page
    'collections.title': 'My Collections',
    'collections.createNew': 'Create New Collection',
    'collections.noCollections': 'No collections yet',
    'collections.startOrganizing': 'Start organizing your recipes',
    'collections.create': 'Create Collection',
    'collections.name': 'Collection Name',
    'collections.description': 'Description',
    'collections.type': 'Type',
    'collections.regular': 'Regular',
    'collections.mealPlan': 'Meal Plan',
    'collections.creating': 'Creating...',
    'collections.cancel': 'Cancel',
    
    // Create/Edit Recipe Page
    'createRecipe.title': 'Create Recipe',
    'createRecipe.editTitle': 'Edit Recipe',
    'createRecipe.basicInfo': 'Basic Information',
    'createRecipe.recipeTitle': 'Recipe Title',
    'createRecipe.description': 'Description',
    'createRecipe.cuisine': 'Cuisine Type',
    'createRecipe.difficulty': 'Difficulty Level',
    'createRecipe.servings': 'Servings',
    'createRecipe.prepTime': 'Prep Time (minutes)',
    'createRecipe.cookTime': 'Cook Time (minutes)',
    'createRecipe.ingredients': 'Ingredients',
    'createRecipe.ingredientsDesc': 'List each ingredient on a new line',
    'createRecipe.instructions': 'Instructions',
    'createRecipe.instructionsDesc': 'Write step-by-step instructions',
    'createRecipe.image': 'Recipe Image',
    'createRecipe.imageUrl': 'Image URL (optional)',
    'createRecipe.tags': 'Tags',
    'createRecipe.tagsDesc': 'Add tags to help people find your recipe',
    'createRecipe.saving': 'Saving...',
    'createRecipe.save': 'Save Recipe',
    'createRecipe.publish': 'Publish Recipe',
    'createRecipe.cancel': 'Cancel',
    
    // Cooking Session Page
    'cookingSession.title': 'Cooking Session',
    'cookingSession.step': 'Step',
    'cookingSession.of': 'of',
    'cookingSession.complete': 'Complete',
    'cookingSession.next': 'Next Step',
    'cookingSession.previous': 'Previous',
    'cookingSession.pause': 'Pause',
    'cookingSession.resume': 'Resume',
    'cookingSession.finish': 'Finish Cooking',
    'cookingSession.startTimer': 'Start Timer',
    'cookingSession.timer': 'Timer',
    'cookingSession.notes': 'Notes',
    'cookingSession.addNote': 'Add a note...',
    
    // Not Found Page
    'notFound.title': '404',
    'notFound.pageNotFound': 'Page not found',
    'notFound.description': "Sorry, we couldn't find the page you're looking for.",
    'notFound.goHome': 'Go back home',
  },
  my: {
    // Navigation
    'nav.home': 'ပင်မစာမျက်နှာ',
    'nav.discover': 'ရှာဖွေမည်',
    'nav.myKitchen': 'ကျွန်ုပ်၏မီးဖိုချောင်',
    'nav.chat': 'စကားပြောမည်',
    'nav.profile': 'ကိုယ်ရေးအကျဉ်း',
    'nav.askAI': 'AI မေးမည်',
    'nav.recipes': 'ချက်နည်းများ',
    'nav.kitchen': 'မီးဖိုချောင်',
    'nav.signIn': 'ဝင်ရောက်မည်',
    'nav.logout': 'ထွက်မည်',
    
    // Home Page
    'home.welcome': 'ပြန်လည်ကြိုဆိုပါတယ်',
    'home.whatToCook': 'ဒီနေ့ ဘာချက်ချင်လဲ?',
    'home.aiAssistant': 'AI လက်ထောက်',
    'home.aiAssistantDesc': 'ချက်ပြုတ်ရေး အကူအညီနှင့် စိတ်ကူးများ ရယူပါ',
    'home.discoverRecipes': 'ချက်နည်းများ ရှာဖွေမည်',
    'home.discoverDesc': 'ချက်နည်းထောင်ပေါင်းများစွာကို ရှာဖွေပါ',
    'home.myKitchen': 'ကျွန်ုပ်၏မီးဖိုချောင်',
    'home.myKitchenDesc': 'စုစည်းမှုများနှင့် သိမ်းဆည်းထားသော ချက်နည်းများ',
    'home.createRecipe': 'ချက်နည်း ဖန်တီးမည်',
    'home.createRecipeDesc': 'သင့်ချက်ပြုတ်မှုကို မျှဝေပါ',
    'home.mealPlan': 'အစားအသောက် အစီအစဉ်',
    'home.mealPlanDesc': 'သင့်အပတ်ကို စီစဉ်ပါ',
    'home.askAI': 'AI ချက်သမားကို မေးမည်',
    'home.suggestedForYou': 'သင့်အတွက် အကြံပြုချက်များ',
    'home.viewAll': 'အားလုံးကြည့်မည်',
    
    // Recipe Card
    'recipe.view': 'ချက်နည်းကြည့်မည်',
    'recipe.edit': 'ပြင်ဆင်မည်',
    'recipe.servings': 'ပန်းကန်',
    
    // Recipe Detail
    'recipeDetail.back': 'နောက်သို့',
    'recipeDetail.failedToLoad': 'ချက်နည်းကို ရယူ၍မရပါ။',
    'recipeDetail.servings': 'ပန်းကန်',
    'recipeDetail.startCooking': 'ချက်ပြုတ်ရန် စတင်မည်',
    'recipeDetail.ingredients': 'ပါဝင်ပစ္စည်းများ',
    'recipeDetail.instructions': 'လုပ်ဆောင်ချက်များ',
    'recipeDetail.noStepsProvided': 'အဆင့်များ မပေးထားပါ။',
    'recipeDetail.reviews': 'သုံးသပ်ချက်များ',
    'recipeDetail.leaveReview': 'သုံးသပ်ချက် ချန်ထားပါ',
    'recipeDetail.shareExperience': 'ဤချက်နည်းနှင့် ပတ်သက်၍ သင့်အတွေ့အကြုံကို မျှဝေပါ... (ရွေးချယ်ပိုင်ခွင့်)',
    'recipeDetail.submitReview': 'သုံးသပ်ချက် တင်သွင်းမည်',
    'recipeDetail.submitting': 'တင်သွင်းနေသည်...',
    'recipeDetail.loginToReview': 'သုံးသပ်ချက် ချန်ထားရန် ကျေးဇူးပြု၍ ဝင်ရောက်ပါ။',
    'recipeDetail.noReviews': 'သုံးသပ်ချက်များ မရှိသေးပါ။ ပထမဦးဆုံး ဖြစ်ပါစေ!',
    'recipeDetail.star': 'ကြယ်',
    'recipeDetail.stars': 'ကြယ်များ',
    'recipeDetail.anonymous': 'အမည်မသိ',
    'recipeDetail.saved': 'သိမ်းဆည်းခဲ့သည်',
    'recipeDetail.removed': 'ဖယ်ရှားခဲ့သည်',
    'recipeDetail.recipeAdded': 'သင့်သိမ်းဆည်းစာရင်းသို့ ချက်နည်းကို ထည့်ခဲ့သည်။',
    'recipeDetail.recipeRemoved': 'သိမ်းဆည်းထားသည်မှ ချက်နည်းကို ဖယ်ရှားခဲ့သည်။',
    'recipeDetail.actionFailed': 'လုပ်ဆောင်ချက် မအောင်မြင်ပါ',
    'recipeDetail.unableToUpdate': 'သိမ်းဆည်းထားသော ချက်နည်းများကို မွမ်းမံ၍မရပါ',
    'recipeDetail.submitted': 'တင်သွင်းခဲ့သည်',
    'recipeDetail.thankYou': 'သင့်တုံ့ပြန်ချက်အတွက် ကျေးဇူးတင်ပါသည်!',
    'recipeDetail.failed': 'မအောင်မြင်ပါ',
    'recipeDetail.unableToSubmit': 'တုံ့ပြန်ချက်ကို တင်သွင်း၍မရပါ',
    'recipeDetail.loginRequired': 'အကောင့်ဝင်ရန် လိုအပ်သည်',
    'recipeDetail.pleaseLogin': 'တုံ့ပြန်ချက် တင်သွင်းရန် ကျေးဇူးပြု၍ အကောင့်ဝင်ပါ။',
    'recipeDetail.ratingRequired': 'အဆင့်သတ်မှတ်ရန် လိုအပ်သည်',
    'recipeDetail.selectRating': 'ကျေးဇူးပြု၍ ကြယ်အဆင့်သတ်မှတ်ပါ။',
    'recipeDetail.loadedSteps': '{count} အဆင့်များကို ရယူခဲ့သည်',
    'recipeDetail.noStepsCheck': 'လုပ်ဆောင်ချက်များ ကဏ္ဍကို စစ်ဆေးပါ။',
    
    // Common
    'common.loading': 'ခေတ္တစောင့်ပါ...',
    'common.error': 'အမှား',
    'common.save': 'သိမ်းမည်',
    'common.cancel': 'မလုပ်တော့',
    'common.delete': 'ဖျက်မည်',
    'common.edit': 'ပြင်ဆင်မည်',
    'common.create': 'ဖန်တီးမည်',
    'common.update': 'မွမ်းမံမည်',
    'common.search': 'ရှာဖွေမည်',
    'common.filter': 'စစ်ထုတ်မည်',
    'common.filters': 'စစ်ထုတ်မှုများ',
    'common.reset': 'ပြန်လည်သတ်မှတ်မည်',
    'common.apply': 'သက်ရောက်စေမည်',
    'common.clear': 'ရှင်းမည်',
    'common.back': 'နောက်သို့',
    'common.next': 'ရှေ့သို့',
    'common.previous': 'ယခင်',
    'common.page': 'စာမျက်နှာ',
    'common.of': 'မှ',
    'common.recipe': 'ချက်နည်း',
    'common.recipes': 'ချက်နည်းများ',
    
    // Index/Home Page
    'index.todaysPlan': 'ယနေ့အစီအစဉ်',
    'index.from': 'မှ',
    'index.mealsPlanned': 'အစာများ စီစဉ်ထား',
    'index.startCooking': 'ချက်ပြုတ်ရန် စတင်မည်',
    'index.viewPlan': 'အစီအစဉ်ကြည့်မည်',
    'index.orAskAnything': 'သို့မဟုတ် အခြားအရာများ မေးမည်',
    'index.whatToCook': 'ဒီနေ့ ဘာချက်ရမလဲ?',
    'index.lookingDifferent': 'အခြားအရာ ရှာနေသလား?',
    'index.askAboutCuisine': 'မြန်မာ အစားအသောက်နှင့် ပတ်သက်၍ အဘယ်အရာမဆို မေးပါ',
    'index.searchPlaceholder': "'အမြန် ညစာ' သို့မဟုတ် 'ကြက်သား အသုံးပြု' စသည်...",
    'index.useChicken': 'ကြက်သား အသုံးပြု',
    'index.quickMeals': 'အမြန် အစာများ',
    'index.spicyDishes': 'စပ်သော အစားအစာများ',
    'index.healthy': 'ကျန်းမာရေး',
    'index.active': 'တက်ကြွ',
    'index.continueWhereLeft': 'သင် ထားခဲ့သည့်နေရာမှ ဆက်လုပ်ပါ',
    'index.started': 'စတင်ခဲ့သည်',
    'index.resumeCooking': 'ချက်ပြုတ်မှု ဆက်လုပ်မည် →',
    'index.tryTonight': 'ဒီညမှာ စမ်းကြည့်ပါ',
    'index.seeAll': 'အားလုံးကြည့်မည် →',
    'index.needMore': 'နောက်ထပ် လိုသလား?',
    'home.forYou': 'သင့်အတွက်',
    'home.forYouSubtitle': 'သင့်အတွက် အထူး ရွေးချယ်ထားသော ချက်နည်းများ',
    'home.seeAll': 'အားလုံးကြည့်မည်',
    'index.mealPlans': 'အစားအသောက် အစီအစဉ်များ',
    'index.myKitchen': 'ကျွန်ုပ်၏မီးဖိုချောင်',
    'index.createRecipe': 'ချက်နည်း ဖန်တီးမည်',
    'index.browseAll': 'အားလုံး ကြည့်ရှုမည်',
    'index.youCooked': 'သင် ချက်ပြုတ်ခဲ့သည်',
    'index.viewHistory': 'သင့် ချက်ပြုတ်မှု သမိုင်း ကြည့်မည် →',
    'index.aiCookingAssistant': 'မြန်မာ အစားအသောက်အတွက် သင့် AI ချက်ပြုတ်ရေး လက်ထောက်',
    'index.fromQuestionToDinner': '"ဘာချက်ရမလဲ?" မှ စားပွဲပေါ် ညစာ အထိ။ ၃၀ စက္ကန့်အတွင်း။',
    'index.getStarted': 'စတင်ပါ',
    'index.signIn': 'ဝင်ရောက်မည်',
    'index.joinHomeCooks': 'မြန်မာ ချက်နည်းများ ရှာဖွေနေသော အိမ်သုံး ချက်သမားများ နှင့် ပူးပေါင်းပါ',
    'index.aiAssistant': 'AI လက်ထောက်',
    'index.aiAssistantDesc': 'ဘာချက်ရမလဲ မေးပါ။ သင့်ရှိသောအရာများအပေါ် အခြေခံ၍ မြန်မာချက်နည်း အကြံပြုချက်များ ချက်ချင်းရယူပါ။',
    'index.stepByStep': 'အဆင့်ဆင့်',
    'index.stepByStepDesc': 'အချိန်တိုင်းကိရိယာများဖြင့် လမ်းညွှန်ချက် အတိုင်း လိုက်နာပါ။ သင်ချက်နေစဉ် AI ကို မေးခွန်းများ မေးပါ။',
    'index.mealPlanning': 'အစာ စီစဉ်ခြင်း',
    'index.mealPlanningDesc': 'သင့်အပတ်ကို ၅ မိနစ်အတွင်း စီစဉ်ပါ။ အစာများ ဆုံးဖြတ်ရာတွင် အချိန်မဖြုန်းပါနှင့်။',
    'index.tryRecipes': 'ဤချက်နည်းများ စမ်းကြည့်ပါ',
    'index.popularDishes': 'စတင်ရန် လူကြိုက်များသော မြန်မာ အစားအစာများ',
    'index.startCookingToday': 'ဒီနေ့ ချက်ပြုတ်မှု စတင်ပါ',
    'index.freeToUse': 'အခမဲ့ အသုံးပြုနိုင်သည်။ ခရက်ဒစ်ကတ် မလိုအပ်ပါ။',
    
    // Discover Page
    'discover.title': 'ချက်နည်းများ',
    'discover.subtitle': 'မြန်မာ စစ်မှန်သော အစားအသောက်များ ရှာဖွေပါ',
    'discover.forYou': 'သင့်အတွက်',
    'discover.community': 'အသိုင်းအဝိုင်း',
    'discover.apply': 'အသုံးပြုမည်',
    'discover.searchPlaceholder': 'ချက်နည်း သို့မဟုတ် ပါဝင်ပစ္စည်းများ ရှာဖွေပါ...',
    'discover.noSuggestions': 'အကြံပြုချက်များ မတွေ့ပါ။',
    'discover.suggestions': 'အကြံပြုချက်များ',
    'discover.trending': 'ခေတ်စား',
    'discover.popular': 'လူကြိုက်များ',
    'discover.quickMeals': 'အမြန် အစာများ',
    'discover.clear': 'ရှင်းမည်',
    'discover.filters': 'စစ်ထုတ်မှုများ',
    'discover.reset': 'ပြန်လည်သတ်မှတ်မည်',
    'discover.diet': 'အစားအသောက်',
    'discover.difficulty': 'ခက်ခဲမှု',
    'discover.maxTime': 'အများဆုံး အချိန်',
    'discover.any': 'မည်သည်မဆို',
    'discover.omnivore': 'အသားနှင့် ဟင်းသီးဟင်းရွက်',
    'discover.vegetarian': 'သက်သတ်လွတ်',
    'discover.vegan': 'သက်သတ်လွတ် (နို့ထွက်ပစ္စည်းမပါ)',
    'discover.easy': 'လွယ်ကူ',
    'discover.medium': 'အလယ်အလတ်',
    'discover.hard': 'ခက်ခဲ',
    'discover.maxCookTime': 'အများဆုံး ချက်ပြုတ်ချိန်',
    'discover.recipesFound': 'ချက်နည်းများ တွေ့ရှိသည်',
    'discover.recipeFound': 'ချက်နည်း တွေ့ရှိသည်',
    'discover.noRecipes': 'ချက်နည်းများ မတွေ့ပါ',
    'discover.tryAdjusting': 'သင့် စစ်ထုတ်မှုများကို ပြင်ဆင်ပါ သို့မဟုတ် အခြားအရာကို ရှာဖွေပါ',
    'discover.clearAllFilters': 'စစ်ထုတ်မှုအားလုံး ရှင်းမည်',
    'discover.previous': 'ယခင်',
    'discover.next': 'ရှေ့သို့',
    'discover.page': 'စာမျက်နှာ',
    'discover.saved': 'သိမ်းဆည်းခဲ့သည်',
    'discover.removed': 'ဖယ်ရှားခဲ့သည်',
    'discover.recipeAdded': 'သင့်သိမ်းဆည်းစာရင်းသို့ ချက်နည်းကို ထည့်ခဲ့သည်။',
    'discover.recipeRemoved': 'သိမ်းဆည်းထားသည်မှ ချက်နည်းကို ဖယ်ရှားခဲ့သည်။',
    'discover.actionFailed': 'လုပ်ဆောင်ချက် မအောင်မြင်ပါ',
    
    // Login Page
    'login.welcomeBack': 'ပြန်လည် ကြိုဆိုပါသည်',
    'login.signInDesc': 'ချက်နည်းများ သိမ်းဆည်းရန်နှင့် လက်ထောက်နှင့် စကားပြောရန် အကောင့်ဝင်ပါ',
    'login.usernameOrEmail': 'အသုံးပြုသူအမည် သို့မဟုတ် အီးမေးလ်',
    'login.usernamePlaceholder': 'အသုံးပြုသူအမည် သို့မဟုတ် အီးမေးလ်',
    'login.password': 'စကားဝှက်',
    'login.forgotPassword': 'စကားဝှက် မေ့နေသလား?',
    'login.rememberMe': 'ကျွန်ုပ်ကို မှတ်ထားပါ',
    'login.signingIn': 'ဝင်ရောက်နေသည်...',
    'login.signIn': 'အကောင့်ဝင်မည်',
    'login.noAccount': 'အကောင့် မရှိသေးဘူးလား?',
    'login.signUp': 'စာရင်းသွင်းမည်',
    'login.termsAgreement': 'ဆက်လုပ်ခြင်းဖြင့် သင်သည် ကျွန်ုပ်တို့၏ စည်းမျဉ်းများနှင့် ကိုယ်ရေးအချက်အလက် မူဝါဒကို သဘောတူသည်။',
    'login.loginFailed': 'အကောင့်ဝင်မှု မအောင်မြင်ပါ။ သင့်အထောက်အထားများကို စစ်ဆေးပါ။',
    
    // Register Page
    'register.createAccount': 'သင့်အကောင့် ဖန်တီးပါ',
    'register.joinDesc': 'မြန်မာ အစားအသောက် ချက်ပြုတ်နေသော ထောင်ပေါင်းများစွာနှင့် ပူးပေါင်းပါ',
    'register.name': 'အမည်အပြည့်အစုံ',
    'register.namePlaceholder': 'သင့်အမည်',
    'register.username': 'အသုံးပြုသူအမည်',
    'register.usernamePlaceholder': 'အသုံးပြုသူအမည် ရွေးချယ်ပါ',
    'register.email': 'အီးမေးလ်',
    'register.emailPlaceholder': 'သင့်@အီးမေးလ်.com',
    'register.password': 'စကားဝှက်',
    'register.passwordPlaceholder': '••••••••',
    'register.confirmPassword': 'စကားဝှက် အတည်ပြုပါ',
    'register.agreeToTerms': 'စည်းမျဉ်းများနှင့် ကိုယ်ရေးအချက်အလက် မူဝါဒကို သဘောတူပါသည်',
    'register.creatingAccount': 'အကောင့် ဖန်တီးနေသည်...',
    'register.signUp': 'စာရင်းသွင်းမည်',
    'register.alreadyHaveAccount': 'အကောင့် ရှိပြီးသား လား?',
    'register.signIn': 'အကောင့်ဝင်မည်',
    'register.passwordMismatch': 'စကားဝှက်များ မကိုက်ညီပါ',
    'register.mustAgreeTerms': 'စည်းမျဉ်းများကို သဘောတူရမည်',
    
    // Profile Page
    'profile.title': 'ကျွန်ုပ်၏ကိုယ်ရေးအကျဉ်း',
    'profile.editProfile': 'ပရိုဖိုင်း ပြင်ဆင်မည်',
    'profile.memberSince': 'အဖွဲ့ဝင်ဖြစ်သည့်အချိန်',
    'profile.activityOverview': 'လှုပ်ရှားမှု အနှစ်ချုပ်',
    'profile.recipesCreated': 'ဖန်တီးထားသော ချက်နည်းများ',
    'profile.recipesSaved': 'သိမ်းဆည်းထားသော ချက်နည်းများ',
    'profile.cookingSessions': 'ချက်ပြုတ်မှု အကြိမ်များ',
    'profile.accountInfo': 'အကောင့်အချက်အလက်',
    'profile.preferences': 'ချက်ပြုတ်ရေး ဦးစားပေးချက်များ',
    'profile.security': 'လုံခြုံရေး',
    'profile.saveChanges': 'ပြောင်းလဲမှုများကို သိမ်းမည်',
    'profile.savingChanges': 'ပြောင်းလဲမှုများကို သိမ်းနေသည်...',
    
    // My Kitchen Page
    'myKitchen.title': 'ကျွန်ုပ်၏မီးဖိုချောင်',
    'myKitchen.savedRecipes': 'သိမ်းဆည်းထားသော ချက်နည်းများ',
    'myKitchen.myRecipes': 'ကျွန်ုပ်၏ချက်နည်းများ',
    'myKitchen.collections': 'စုစည်းမှုများ',
    'myKitchen.mealPlans': 'အစားအသောက် အစီအစဉ်များ',
    'myKitchen.noSaved': 'သိမ်းဆည်းထားသော ချက်နည်းများ မရှိသေးပါ',
    'myKitchen.startSaving': 'သင့် အကြိုက်ဆုံး ချက်နည်းများကို သိမ်းဆည်းစတင်ပါ',
    'myKitchen.browseRecipes': 'ချက်နည်းများ ကြည့်ရှုမည်',
    
    // Collections Page
    'collections.title': 'ကျွန်ုပ်၏စုစည်းမှုများ',
    'collections.createNew': 'စုစည်းမှုအသစ် ဖန်တီးမည်',
    'collections.noCollections': 'စုစည်းမှုများ မရှိသေးပါ',
    'collections.startOrganizing': 'သင့်ချက်နည်းများကို စုစည်းစတင်ပါ',
    'collections.create': 'စုစည်းမှု ဖန်တီးမည်',
    'collections.name': 'စုစည်းမှု အမည်',
    'collections.description': 'ဖော်ပြချက်',
    'collections.type': 'အမျိုးအစား',
    'collections.regular': 'ပုံမှန်',
    'collections.mealPlan': 'အစားအသောက် အစီအစဉ်',
    'collections.creating': 'ဖန်တီးနေသည်...',
    'collections.cancel': 'မလုပ်တော့',
    
    // Create/Edit Recipe Page
    'createRecipe.title': 'ချက်နည်း ဖန်တီးမည်',
    'createRecipe.editTitle': 'ချက်နည်း ပြင်ဆင်မည်',
    'createRecipe.basicInfo': 'အခြေခံ အချက်အလက်',
    'createRecipe.recipeTitle': 'ချက်နည်း ခေါင်းစဉ်',
    'createRecipe.description': 'ဖော်ပြချက်',
    'createRecipe.cuisine': 'အစားအသောက် အမျိုးအစား',
    'createRecipe.difficulty': 'ခက်ခဲမှု အဆင့်',
    'createRecipe.servings': 'ပန်းကန်',
    'createRecipe.prepTime': 'ပြင်ဆင်ချိန် (မိနစ်)',
    'createRecipe.cookTime': 'ချက်ပြုတ်ချိန် (မိနစ်)',
    'createRecipe.ingredients': 'ပါဝင်ပစ္စည်းများ',
    'createRecipe.ingredientsDesc': 'ပါဝင်ပစ္စည်း တစ်ခုချင်းစီကို စာကြောင်းအသစ်တွင် ထည့်ပါ',
    'createRecipe.instructions': 'လုပ်ဆောင်ချက်များ',
    'createRecipe.instructionsDesc': 'အဆင့်ဆင့် လမ်းညွှန်ချက်များ ရေးပါ',
    'createRecipe.image': 'ချက်နည်း ပုံ',
    'createRecipe.imageUrl': 'ပုံ URL (ရွေးချယ်ပိုင်ခွင့်)',
    'createRecipe.tags': 'တဂ်များ',
    'createRecipe.tagsDesc': 'လူများက သင့်ချက်နည်းကို ရှာရန် တဂ်များ ထည့်ပါ',
    'createRecipe.saving': 'သိမ်းနေသည်...',
    'createRecipe.save': 'ချက်နည်း သိမ်းမည်',
    'createRecipe.publish': 'ချက်နည်း ထုတ်ဝေမည်',
    'createRecipe.cancel': 'မလုပ်တော့',
    
    // Cooking Session Page
    'cookingSession.title': 'ချက်ပြုတ်မှု အစည်းအဝေး',
    'cookingSession.step': 'အဆင့်',
    'cookingSession.of': 'မှ',
    'cookingSession.complete': 'ပြီးစီးသည်',
    'cookingSession.next': 'နောက်အဆင့်',
    'cookingSession.previous': 'ယခင်',
    'cookingSession.pause': 'ခဏရပ်မည်',
    'cookingSession.resume': 'ပြန်စမည်',
    'cookingSession.finish': 'ချက်ပြုတ်မှု ပြီးဆုံးမည်',
    'cookingSession.startTimer': 'အချိန်တိုင်း စတင်မည်',
    'cookingSession.timer': 'အချိန်တိုင်း',
    'cookingSession.notes': 'မှတ်စုများ',
    'cookingSession.addNote': 'မှတ်စု ထည့်ပါ...',
    
    // Not Found Page
    'notFound.title': '404',
    'notFound.pageNotFound': 'စာမျက်နှာ မတွေ့ပါ',
    'notFound.description': 'စိတ်မကောင်းပါဘူး၊ သင် ရှာနေသော စာမျက်နှာကို ကျွန်ုပ်တို့ ရှာမတွေ့ပါ။',
    'notFound.goHome': 'ပင်မစာမျက်နှာ ပြန်သွားမည်',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved === 'my' ? 'my' : 'en') as Language;
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
